const plugin = require("tailwindcss/plugin");
const forms = require("@tailwindcss/forms");
const typography = require("@tailwindcss/typography");
const containerQueries = require("@tailwindcss/container-queries");

const colorVar = (name, fallback) => `var(--color-${name}, ${fallback})`;
const radiusVar = (name, fallback) => `var(--radius-${name}, ${fallback})`;
const shadowVar = (name, fallback) => `var(--shadow-${name}, ${fallback})`;

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
    "./index.html",
    "./workspace.html",
    "./pages/**/*.html",
  ],
  theme: {
    extend: {
      colors: {
        primary: colorVar("primary", "#3BDEC8"),
        secondary: colorVar("secondary", "#1a1a1a"),
        tertiary: colorVar("tertiary", "#6e5e00"),
        quaternary: colorVar("quaternary", "#ffe66d"),
        "background-light": colorVar("background-light", "#FDF9F0"),
        "background-dark": colorVar("background-dark", "#18181b"),
        "text-light": colorVar("text-light", "#111111"),
        "text-dark": colorVar("text-dark", "#ededed"),
        "card-light": colorVar("card-light", "#ffffff"),
        "card-dark": colorVar("card-dark", "#1E1E1E"),
        "accent-yellow": colorVar("accent-yellow", "#FFEB3B"),
        "accent-pink": colorVar("accent-pink", "#FF69B4"),
        "accent-orange": colorVar("accent-orange", "#FF6B6B"),
        "accent-green": colorVar("accent-green", "#7FFF00"),
        "accent-purple": colorVar("accent-purple", "#D8BFD8"),
        "accent-blue": colorVar("accent-blue", "#3b82f6"),
        "accent-red": colorVar("accent-red", "#FF3333"),
        ink: colorVar("ink", "#151515"),
        paper: colorVar("paper", "#ffffff"),
        cream: colorVar("cream", "#f7f4ef"),
        teal: colorVar("teal", "#008080"),
        "teal-light": colorVar("teal-light", "#20B2AA"),
        "teal-accent": colorVar("teal-accent", "#0d9488"),
        orange: colorVar("orange", "#FF7F50"),
        pink: colorVar("pink", "#FF69B4"),
        "pink-accent": colorVar("pink-accent", "#db2777"),
        "text-main": colorVar("text-main", "#1A1A1A"),
        "retro-black": colorVar("retro-black", "#1a1a1a"),
        surface: colorVar("surface", "#fcf9f8"),
        "surface-dim": colorVar("surface-dim", "#dcd9d9"),
        "surface-bright": colorVar("surface-bright", "#fcf9f8"),
        "surface-container-lowest": colorVar("surface-container-lowest", "#ffffff"),
        "surface-container-low": colorVar("surface-container-low", "#f6f3f2"),
        "surface-container": colorVar("surface-container", "#f0eded"),
        "surface-container-high": colorVar("surface-container-high", "#eae7e7"),
        "surface-container-highest": colorVar("surface-container-highest", "#e5e2e1"),
        "surface-variant": colorVar("surface-variant", "#e5e2e1"),
        "surface-tint": colorVar("surface-tint", "#006b57"),
        "on-surface": colorVar("on-surface", "#1b1b1b"),
        "on-surface-variant": colorVar("on-surface-variant", "#3a4a44"),
        background: colorVar("background", "#fcf9f8"),
        "on-background": colorVar("on-background", "#1b1b1b"),
        outline: colorVar("outline", "#6a7b74"),
        "outline-variant": colorVar("outline-variant", "#b9cbc3"),
        "inverse-primary": colorVar("inverse-primary", "#00e0b7"),
        "inverse-surface": colorVar("inverse-surface", "#313030"),
        "inverse-on-surface": colorVar("inverse-on-surface", "#f3f0ef"),
        "primary-fixed": colorVar("primary-fixed", "#15ffd1"),
        "primary-fixed-dim": colorVar("primary-fixed-dim", "#00e0b7"),
        "primary-container": colorVar("primary-container", "#00ffd1"),
        "on-primary": colorVar("on-primary", "#ffffff"),
        "on-primary-container": colorVar("on-primary-container", "#00725c"),
        "on-primary-fixed": colorVar("on-primary-fixed", "#002019"),
        "on-primary-fixed-variant": colorVar("on-primary-fixed-variant", "#005141"),
        "secondary-fixed": colorVar("secondary-fixed", "#ffdbc9"),
        "secondary-fixed-dim": colorVar("secondary-fixed-dim", "#ffb68d"),
        "secondary-container": colorVar("secondary-container", "#fc8a40"),
        "on-secondary": colorVar("on-secondary", "#ffffff"),
        "on-secondary-container": colorVar("on-secondary-container", "#672c00"),
        "on-secondary-fixed": colorVar("on-secondary-fixed", "#331200"),
        "on-secondary-fixed-variant": colorVar("on-secondary-fixed-variant", "#763300"),
        "tertiary-container": colorVar("tertiary-container", "#ffe253"),
        "tertiary-fixed": colorVar("tertiary-fixed", "#ffe253"),
        "tertiary-fixed-dim": colorVar("tertiary-fixed-dim", "#e1c639"),
        "on-tertiary": colorVar("on-tertiary", "#ffffff"),
        "on-tertiary-container": colorVar("on-tertiary-container", "#746400"),
        "on-tertiary-fixed": colorVar("on-tertiary-fixed", "#211b00"),
        "on-tertiary-fixed-variant": colorVar("on-tertiary-fixed-variant", "#534600"),
        error: colorVar("error", "#ba1a1a"),
        "error-container": colorVar("error-container", "#ffdad6"),
        "on-error": colorVar("on-error", "#ffffff"),
        "on-error-container": colorVar("on-error-container", "#93000a"),
      },
      fontFamily: {
        display: ["var(--font-display)", "sans-serif"],
        body: ["var(--font-body)", "sans-serif"],
        serif: ["var(--font-serif)", "serif"],
        marker: ["var(--font-marker)", "cursive"],
        cursive: ["var(--font-cursive)", "cursive"],
        script: ["var(--font-script)", "cursive"],
        "headline-md": ["var(--font-headline-md)", "sans-serif"],
        "headline-lg": ["var(--font-headline-lg)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-headline-lg-mobile)", "sans-serif"],
        "display-lg": ["var(--font-display-lg)", "sans-serif"],
        "body-lg": ["var(--font-body-lg)", "sans-serif"],
        "body-md": ["var(--font-body-md)", "sans-serif"],
        "label-md": ["var(--font-label-md)", "sans-serif"],
        "label-sm": ["var(--font-label-sm)", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "700" }],
      },
      borderRadius: {
        DEFAULT: radiusVar("default", "0.5rem"),
        lg: radiusVar("lg", "1rem"),
        xl: radiusVar("xl", "1.5rem"),
        "2xl": radiusVar("2xl", "4rem"),
        full: "9999px",
      },
      boxShadow: {
        retro: shadowVar("retro", "4px 4px 0px 0px rgba(0,0,0,1)"),
        "retro-hover": shadowVar("retro-hover", "2px 2px 0px 0px rgba(0,0,0,1)"),
        "retro-dark": shadowVar("retro-dark", "4px 4px 0px 0px #39FFCA"),
        sticker: shadowVar("sticker", "2px 2px 0px 0px rgba(0,0,0,0.8)"),
        hard: shadowVar("hard", "6px 6px 0 #000"),
        brutal: shadowVar("brutal", "8px 8px 0px #000000"),
        "brutal-sm": shadowVar("brutal-sm", "4px 4px 0px #000000"),
      },
      spacing: {
        base: "8px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        "stack-md": "24px",
        "stack-lg": "40px",
        "stack-sm": "12px",
        gutter: "24px",
      },
      animation: {
        "float-1": "float 6s ease-in-out infinite",
        "float-2": "float 7s ease-in-out infinite 0.5s",
        "float-3": "float 5s ease-in-out infinite 1s",
        "float-4": "float 8s ease-in-out infinite 1.5s",
        "float-5": "float 9s ease-in-out infinite 2s",
        "float-6": "float 6.5s ease-in-out infinite 0.2s",
        marquee: "marquee 25s linear infinite",
        draw: "draw 0.4s ease-in-out forwards",
        "bounce-slow": "bounce 3s infinite",
        wiggle: "wiggle 1s ease-in-out infinite",
        float: "float 5s ease-in-out infinite",
        "float-reverse": "float-reverse 6s ease-in-out infinite",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-15px)" },
        },
        "float-reverse": {
          "0%, 100%": { transform: "translateY(0px) rotate(0deg)" },
          "50%": { transform: "translateY(15px) rotate(-3deg)" },
        },
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-100%)" },
        },
        draw: {
          "0%": { strokeDasharray: "0 100", opacity: "0" },
          "10%": { opacity: "1" },
          "100%": { strokeDasharray: "100 0", opacity: "1" },
        },
        wiggle: {
          "0%, 100%": { transform: "rotate(-3deg)" },
          "50%": { transform: "rotate(3deg)" },
        },
      },
    },
  },
  plugins: [
    forms,
    typography,
    containerQueries,
    plugin(({ addVariant }) => {
      addVariant("children", "& > *");
    }),
  ],
};
